### ISSUE TITLE
Consider open license

### ISSUE THREAD

**Issue by stijnb1234** [HomerBond005/RedstoneCommand#2]
I know it's a long time ago, but could you consider a license that's a bit more open, like allowing distribution? I've made a version for the latest versions of Spigot, but I can't distribute because of the license.

**Comment by HomerBond005** [comment]
Happy to see someone still using this code and caring about software licenses :)

Changed license to MIT, feel free to distribute your version

**Comment by stijnb1234** [comment]
Thanks a lot!
